name: deploy

on:
  push:
    branches:
      - master
    paths:
      - "src/**"
  pull_request:
    branches:
      - master
    paths:
      - "src/**"
jobs:
  deploy:
    if: >
      github.event_name == 'push' ||
      (github.event_name == 'pull_request' &&
       github.event.pull_request.base.ref == 'master' &&
       (github.event.pull_request.author_association == 'OWNER' ||
        github.event.pull_request.author_association == 'COLLABORATOR'))
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: "pip"

      - name: Install dependencies
        run: pip install -r requirements.txt

      #  Verificación de compilación
      - name: Validar que los archivos Typst compilan sin errores
        run: |
          # Intenta compilar los archivos principales sin generar salida
          # Esto asegura que no hay errores de sintaxis o fallos antes de generar archivos reales
          touying compile --root=src --output=/dev/null src/main.typ
          touying compile --root=src --output=/dev/null src/main-en.typ

      - name: Make build dir
        run: mkdir build

      - name: Build HTML slides
        run: |
          # Spanish versions
          touying compile --root=src --output="build/index.html"                                       src/main.typ
          touying compile --root=src --output="build/4-3.html"   --sys-inputs '{"aspect-ratio":"4-3"}' src/main.typ
          # English versions
          touying compile --root=src --output="build/en.html"                                          src/main-en.typ
          touying compile --root=src --output="build/en-4-3.html" --sys-inputs '{"aspect-ratio":"4-3"}' src/main-en.typ

      - name: Build PDF slides
        run: |
          # Spanish versions
          touying compile --root=src --format=pdf --output="build/diapositivas.pdf"                                           src/main.typ
          touying compile --root=src --format=pdf --output="build/diapositivas-4-3.pdf" --sys-inputs '{"aspect-ratio":"4-3"}' src/main.typ
          # English versions  
          touying compile --root=src --format=pdf --output="build/slides-en.pdf"                                              src/main-en.typ
          touying compile --root=src --format=pdf --output="build/slides-en-4-3.pdf"    --sys-inputs '{"aspect-ratio":"4-3"}' src/main-en.typ

      - name: Build PDF handouts
        run: |
          # Spanish versions
          touying compile --root=src --format=pdf --output="build/handout.pdf"     --sys-inputs '{"handout":"true"}'                       src/main.typ
          touying compile --root=src --format=pdf --output="build/handout-4-3.pdf" --sys-inputs '{"handout":"true", "aspect-ratio":"4-3"}' src/main.typ
          # English versions
          touying compile --root=src --format=pdf --output="build/handout-en.pdf"     --sys-inputs '{"handout":"true"}'                       src/main-en.typ
          touying compile --root=src --format=pdf --output="build/handout-en-4-3.pdf" --sys-inputs '{"handout":"true", "aspect-ratio":"4-3"}' src/main-en.typ


      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "build/"

      # Deploy to GitHub Pages only on push events
      - name: Deploy to GitHub Pages
        if: github.event_name == 'push'
        id: deployment
        uses: actions/deploy-pages@v4
